spring:
  payments:
    phonepe:
      merchantId: PGTESTPAYUAT
      saltKey: 099eb0cd-02cf-4e2a-8aca-3e6c6aff0399
      saltIndex: 1
      env: UAT
      shouldPublishEvents: true
      callbackUrl: http://localhost:8080/pay-return-url
razorpay:
  rzp_key_id: rzp_test_XDw7UM5Ne41EzZ
  rzp_key_secret: IGKt94kKjt3gn9keKjTJEddO
  rzp_currency: INR
  rzp_company_name: PLUGIN
